spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_shiro?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  application:
    name: spring-shiro
  http:
    encoding:
      charset: utf-8
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true