spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_jpa?userSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true